### ISSUE TITLE
Writing compressed VDBs in houdini

### ISSUE THREAD

**Issue by MeghaS94** [dreamworksanimation/openvdb#153]
I feel like there should be a straightforward way to write compressed VDB's, however I am not able to get the compressed files from houdini 15 (a VDB points grid, using the openVDB write node). I am however able to get gzipped VDB's from houdini 16 file write node. 
How do I write out a compressed VDB in houdini 15? Also I notice that there is a small difference (about 0.2 KB ) between the files written from houdini 15 vs 16, why does this happen?

**Comment by danrbailey** [comment]
Hi @MeghaS94 , 

If you use the native Geometry ROP in Houdini 15 or Houdini 16, your VDB files will always be (Blosc) compressed. You only have the UI option to choose the compression type when using the OpenVDB Write SOP, though note that you need to pass the -DOPENVDB_USE_BLOSC flag to the compiler to build the OpenVDB Write SOP with support for Blosc compression. We recommend using Blosc over GZip due to significantly improved compression for slightly larger file sizes,

If you're writing out files with VDB Points, these grid types are only supported in Houdini 16 natively, so you'll need to install the open-source nodes in Houdini 15 to be able to use them there, but then you can either use the OpenVDB Write SOP or the native Geometry ROP.

Regarding the difference in file size, we did tune the Blosc compression settings slightly to obtain better compression in OpenVDB 4.0, but I suspect in your case this might be down to storing slightly different metadata in the file between Houdini versions. Either way, nothing to be too concerned about.

**Comment by MeghaS94** [comment]
That helped! Thank you
