### ISSUE TITLE
openvdb::points::appendAttribute crash when using 3x3 Matrix type

### ISSUE THREAD

**Issue by dokipen3d** [dreamworksanimation/openvdb#185]
Trying to append an attribute of matrix 3 type causes a crash. Matrix4 types works fine though

I had a forum post here....
http://www.openvdb.org/forum/?place=msg%2Fopenvdb-forum%2Fvp1wU6Eam8w%2F25p_KhA1CgAJ

**Comment by danrbailey** [comment]
Thanks for reporting and sorry I missed your last forum post.

It turns out this is actually not an issue with appendAttribute itself, but the fact that appendAttribute depends on there being a valid zeroVal<> specialisation for the value type. As there are no zeroVal specialisations for Mat3 types, the crash is caused by dereferencing a null pointer.

I've fixed this issue and added native Mat3 attribute support in this PR:

https://github.com/dreamworksanimation/openvdb/pull/186

**Comment by dokipen3d** [comment]
I'm currently building the branch from your repo Dan. Can I ignore the TestMath errors?

**Comment by dokipen3d** [comment]
Also compiling this branch is giving some issues with the libraries building strangely. They all compile and link but doing an ld on them gives....
"warning: cannot find entry symbol _start; not setting start address" 

...which according to google, is the main function not being found (which being a shared library is a bit odd). There is also a a.out being created. Not completely sure it's being build as a shared library.

**Comment by dokipen3d** [comment]
I made a PR to fix the unit tests. 
https://github.com/danrbailey/openvdb/pull/1
