### ISSUE TITLE
 OpenVDB Cookbook 

### ISSUE THREAD

**Issue by MichaelQuell** [dreamworksanimation/openvdb#244]
I am trying to learn about the library.
At the moment i am stuck at http://www.openvdb.org/documentation/doxygen/codeExamples.html#sModifyingGrids

the last line in the example "grid->setBackground(0.0);" seems to be outdated since v3.0.0 . I tried fixing it using  openvdb::tools::changeBackground() as suggested, but i dont seem to get the arguments right. Could one point out what to do?

**Comment by OpenVDB-DevTeam** [comment]
The cookbook examples have been updated as of the latest commit (81c29cee).  For the record, the replacement for "`grid->setBackground(0.0)`" is "`openvdb::tools::changeBackground(grid->tree(), 0.0)`".

**Comment by dokipen3d** [comment]
Just out of curiosity, what was the reason for removing member functions from the grid and moving functionality to tools?

**Comment by OpenVDB-DevTeam** [comment]
We try to keep core data structures like `Grid` and `Tree` as lean as possible, both for code maintenance reasons (there are multiple `LeafNode` specializations that need to be kept in sync, for example) and because they get included more or less everywhere.  The `NodeManager` class introduced in OpenVDB 3.0 provides a generic means of tree traversal that allows algorithms like pruning to be factored out of those core tree classes.
